name: App Publish

on:
  push:
    branches:
      - main
      - release/**
    paths:
      - version.json
      - .github/workflows/app-publish.yml
      - Directory.Build.props
      - 'src/Application/**'
      - 'src/Extensions/**'
      - 'src/ClientSDK/DotNet/**'
      - 'src/Shared/**'
      - 'src/Setup/**'
      - 'src/Template/**'
      - '!**/*.md'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    env:
      IS_CI: true
      Solution_Name: SDK.sln
      Launcher_csproj: src\Application\Launcher\Launcher.csproj
      App_csproj: src\Application\Raid.Toolkit\Raid.Toolkit.csproj
      Client_csproj: src\ClientSDK\DotNet\Raid.Client.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set branch-based environment variables
        shell: pwsh
        run: |
          if ("${{ github.ref_name }}" -eq "main") {
            echo "PRERELEASE=true" >> $env:GITHUB_ENV
            echo "PRERELEASEN=1" >> $env:GITHUB_ENV
          } else {
            echo "PRERELEASE=false" >> $env:GITHUB_ENV
            echo "PRERELEASEN=0" >> $env:GITHUB_ENV
          }

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.0.x
            6.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Set version with nbgv
        uses: dotnet/nbgv@master
        id: rtk_version
        with:
          setAllVars: true

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

      - name: Build Project
        run: msbuild $env:Solution_Name -m -t:"Build;Pack" -p:Configuration=Release -p:Platform=x64 -p:PackageOutputPath="$(Get-Location)\publish\nuget"

      - name: Build Launcher
        run: msbuild $env:Launcher_csproj -m -t:Publish -p:TargetFramework=net5.0-windows -p:Configuration=Release -p:Platform=x64 -p:PublishDir="$(Get-Location)\publish\RTK"

      - name: Build Setup
        run: |
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          heat.exe dir $env:BuildOutputDirectory -cg RaidToolkitBinaries -out out\RaidToolkitBinaries.wxs -dr BINDIR -srd -suid -sreg -g1 -var env.BuildOutputDirectory -ag
          candle.exe -nologo -o out\ out\RaidToolkitBinaries.wxs Product.wxs Registry.wxs Bundle.wxs -ext WixBalExtension
          light.exe -nologo -o out\RaidToolkit.msi out\Product.wixobj out\Registry.wixobj out\RaidToolkitBinaries.wixobj -ext WixBalExtension
          light.exe -nologo -o out\RaidToolkitSetup.exe out\Bundle.wixobj -ext WixBalExtension
        working-directory: ./src/Setup
        env:
          AppVersion: ${{ steps.rtk_version.outputs.Version }}
          Prerelease: ${{ env.PRERELEASEN }}
          BuildOutputDirectory: ..\Application\Raid.Toolkit\bin\x64\Release\net6.0-windows10.0.19041.0\win10-x64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.rtk_version.outputs.Version }}
          prerelease: ${{ env.PRERELEASE }}
          body_path: CHANGES.md
          fail_on_unmatched_files: false
          files: |
            UPGRADE_2.0.md
            publish/RTK/Raid.Toolkit.exe
            src/Setup/out/RaidToolkitSetup.exe
            src/Template/vsix/bin/release/RTKExtensionTemplate.vsix
            ThirdPartyNotice.txt
